# Specify the Docker image to use for the Gitpod workspace
image: leanprovercommunity/mathlib:gitpod

# Configure VS Code settings
vscode:
  extensions:
    - leanprover.lean4  # Lean 4 support extension for VS Code

# Define tasks to run in the Gitpod workspace
tasks:
  - init: |
      # Update elan (Lean toolchain manager) to the latest version
      elan self update
      # Retrieve and cache the latest Mathlib dependencies
      lake exe cache get