name: Pull Request
# Trigger the workflow on pull request events
on:
  pull_request:
    branches: ["main"] # Trigger on pull requests targeting the "main" branch (replace "main" with your default branch if different)
  workflow_dispatch: # Allow manual triggering of the workflow from the GitHub Actions interface

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y

      - name: Get cache
        run: ~/.elan/bin/lake exe cache get

      - name: Build project
        run: ~/.elan/bin/lake build Project

      - name: Build blueprint and copy to `docs/blueprint`
        uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20231201
          run: |
            # Install necessary dependencies and build the blueprint
            export PIP_BREAK_SYSTEM_PACKAGES=1
            apk update
            apk add --update make py3-pip git pkgconfig graphviz graphviz-dev gcc musl-dev
            git config --global --add safe.directory $GITHUB_WORKSPACE
            git config --global --add safe.directory `pwd`
            python3 -m venv env
            source env/bin/activate
            pip install --upgrade pip requests wheel
            pip install pygraphviz --global-option=build_ext --global-option="-L/usr/lib/graphviz/" --global-option="-R/usr/lib/graphviz/"
            pip install leanblueprint
            leanblueprint pdf
            leanblueprint web

      - name: Check declarations
        run: ~/.elan/bin/lake exe checkdecls blueprint/lean_decls
